- id: p_exam_battle_config-davi-01-produce-001-1-2
  turn: 9
  vocal: 67
  dance: 168
  visual: 101
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-01-produce-001-1
- id: p_exam_battle_config-davi-01-produce-001-2-2
  turn: 11
  vocal: 178
  dance: 444
  visual: 266
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-01-produce-001-2
- id: p_exam_battle_config-davi-01-produce-002-1-2
  turn: 9
  vocal: 127
  dance: 319
  visual: 191
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-01-produce-002-1
- id: p_exam_battle_config-davi-01-produce-002-2-2
  turn: 11
  vocal: 381
  dance: 953
  visual: 572
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-01-produce-002-2
- id: p_exam_battle_config-davi-01-seminar_gruop-03-2
  turn: 6
  vocal: 2000
  dance: 4000
  visual: 2500
  produceExamBattleScoreConfigId: p_exam_battle_score_config-seminar_gruop-03-2
- id: p_exam_battle_config-davi-02-produce-001-1-1
  turn: 9
  vocal: 57
  dance: 203
  visual: 78
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-02-produce-001-1
- id: p_exam_battle_config-davi-02-produce-001-2-1
  turn: 12
  vocal: 152
  dance: 535
  visual: 205
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-02-produce-001-2
- id: p_exam_battle_config-davi-02-produce-002-1-1
  turn: 9
  vocal: 109
  dance: 384
  visual: 147
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-02-produce-002-1
- id: p_exam_battle_config-davi-02-produce-002-2-1
  turn: 12
  vocal: 326
  dance: 1149
  visual: 440
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-02-produce-002-2
- id: p_exam_battle_config-davi-04-produce-001-1-2
  turn: 9
  vocal: 50
  dance: 151
  visual: 134
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-04-produce-001-1
- id: p_exam_battle_config-davi-04-produce-001-2-2
  turn: 11
  vocal: 133
  dance: 399
  visual: 355
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-04-produce-001-2
- id: p_exam_battle_config-davi-04-produce-002-1-2
  turn: 9
  vocal: 95
  dance: 286
  visual: 255
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-04-produce-002-1
- id: p_exam_battle_config-davi-04-produce-002-2-2
  turn: 11
  vocal: 286
  dance: 857
  visual: 762
  produceExamBattleScoreConfigId: p_exam_battle_score_config-davi-04-produce-002-2
- id: p_exam_battle_config-tutorial_fktn
  turn: 4
  vocal: 65
  dance: 110
  visual: 80
  produceExamBattleScoreConfigId: p_exam_battle_score_config-tutorial-fktn
- id: p_exam_battle_config-tutorial_hski
  turn: 4
  vocal: 65
  dance: 80
  visual: 110
  produceExamBattleScoreConfigId: p_exam_battle_score_config-tutorial-hski
- id: p_exam_battle_config-tutorial_ttmr
  turn: 4
  vocal: 110
  dance: 80
  visual: 65
  produceExamBattleScoreConfigId: p_exam_battle_score_config-tutorial-ttmr
- id: p_exam_battle_config-vida-03-produce-001-1-1
  turn: 9
  vocal: 90
  dance: 110
  visual: 134
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-001-1
- id: p_exam_battle_config-vida-03-produce-001-1-2
  turn: 9
  vocal: 90
  dance: 110
  visual: 134
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-001-1
- id: p_exam_battle_config-vida-03-produce-001-2-1
  turn: 12
  vocal: 238
  dance: 291
  visual: 353
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-001-2
- id: p_exam_battle_config-vida-03-produce-001-2-2
  turn: 11
  vocal: 238
  dance: 291
  visual: 353
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-001-2
- id: p_exam_battle_config-vida-03-produce-002-1-1
  turn: 9
  vocal: 171
  dance: 209
  visual: 253
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-002-1
- id: p_exam_battle_config-vida-03-produce-002-1-2
  turn: 9
  vocal: 171
  dance: 209
  visual: 253
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-002-1
- id: p_exam_battle_config-vida-03-produce-002-2-1
  turn: 12
  vocal: 512
  dance: 626
  visual: 758
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-002-2
- id: p_exam_battle_config-vida-03-produce-002-2-2
  turn: 11
  vocal: 512
  dance: 626
  visual: 758
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vida-03-produce-002-2
- id: p_exam_battle_config-vivo-01-seminar_gruop-03-3
  turn: 6
  vocal: 2500
  dance: 2000
  visual: 4000
  produceExamBattleScoreConfigId: p_exam_battle_score_config-seminar_gruop-03-3
- id: p_exam_battle_config-voda-01-produce-001-1-1
  turn: 9
  vocal: 168
  dance: 101
  visual: 67
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-01-produce-001-1
- id: p_exam_battle_config-voda-01-produce-001-2-1
  turn: 12
  vocal: 444
  dance: 266
  visual: 178
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-01-produce-001-2
- id: p_exam_battle_config-voda-01-produce-002-1-1
  turn: 9
  vocal: 319
  dance: 191
  visual: 127
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-01-produce-002-1
- id: p_exam_battle_config-voda-01-produce-002-2-1
  turn: 12
  vocal: 953
  dance: 572
  visual: 381
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-01-produce-002-2
- id: p_exam_battle_config-voda-01-seminar_gruop-03-1
  turn: 6
  vocal: 4000
  dance: 2500
  visual: 2000
  produceExamBattleScoreConfigId: p_exam_battle_score_config-seminar_gruop-03-1
- id: p_exam_battle_config-voda-01-seminar_gruop-03-4
  turn: 6
  vocal: 4000
  dance: 2500
  visual: 2000
  produceExamBattleScoreConfigId: p_exam_battle_score_config-seminar_gruop-03-4
- id: p_exam_battle_config-voda-03-produce-001-1-2
  turn: 9
  vocal: 134
  dance: 110
  visual: 90
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-03-produce-001-1
- id: p_exam_battle_config-voda-03-produce-001-2-2
  turn: 11
  vocal: 353
  dance: 291
  visual: 238
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-03-produce-001-2
- id: p_exam_battle_config-voda-03-produce-002-1-2
  turn: 9
  vocal: 253
  dance: 209
  visual: 171
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-03-produce-002-1
- id: p_exam_battle_config-voda-03-produce-002-2-2
  turn: 11
  vocal: 758
  dance: 626
  visual: 512
  produceExamBattleScoreConfigId: p_exam_battle_score_config-voda-03-produce-002-2
- id: p_exam_battle_config-vovi-04-produce-001-1-1
  turn: 9
  vocal: 151
  dance: 50
  visual: 134
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vovi-04-produce-001-1
- id: p_exam_battle_config-vovi-04-produce-001-2-1
  turn: 12
  vocal: 399
  dance: 133
  visual: 355
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vovi-04-produce-001-2
- id: p_exam_battle_config-vovi-04-produce-002-1-1
  turn: 9
  vocal: 286
  dance: 95
  visual: 255
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vovi-04-produce-002-1
- id: p_exam_battle_config-vovi-04-produce-002-2-1
  turn: 12
  vocal: 857
  dance: 286
  visual: 762
  produceExamBattleScoreConfigId: p_exam_battle_score_config-vovi-04-produce-002-2