- id: pvp_rate_config-1
  description: 初めてのコンテスト
  vocal: 353
  dance: 238
  visual: 291
  examSettingId: p_exam_setting-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-contest-season_001
  examBattleFirstRankBonusPermil: 200
  pvpRateCommonProduceCardId: pvp_live_battle_1
  winTimelineAssetId: tln_cont_vovi-001_totalresult_win
  loseTimelineAssetId: tln_cont_vovi-001_totalresult_lose
  startTimelineInitialTimePermil: 5033
  topAssetId: contest-top-vovi
  stages:
  - stageType: PvpRateStageType__1
    planType: ProducePlanType_Common
    turn: 12
    produceItemId: pitem_00-0-004-0-000
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle
  - stageType: PvpRateStageType__2
    planType: ProducePlanType_Plan1
    turn: 8
    produceItemId: pitem_01-0-005-0-000
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle
  - stageType: PvpRateStageType__3
    planType: ProducePlanType_Plan2
    turn: 8
    produceItemId: pitem_02-0-002-0-000
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle
- id: pvp_rate_config-2
  description: S2
  vocal: 291
  dance: 353
  visual: 238
  examSettingId: p_exam_setting-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-contest-season_002
  examBattleFirstRankBonusPermil: 200
  pvpRateCommonProduceCardId: pvp_live_battle_1
  winTimelineAssetId: tln_cont_voda-001_totalresult_win
  loseTimelineAssetId: tln_cont_voda-001_totalresult_lose
  startTimelineInitialTimePermil: 5033
  topAssetId: contest-top-voda
  stages:
  - stageType: PvpRateStageType__1
    planType: ProducePlanType_Common
    turn: 12
    produceItemId: pitem_00-0-004-0-001
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_voda-001_start
    examTimelineAssetId: tln_cont_voda-001_battle
  - stageType: PvpRateStageType__2
    planType: ProducePlanType_Plan1
    turn: 12
    produceItemId: pitem_01-0-005-0-001
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_voda-001_start
    examTimelineAssetId: tln_cont_voda-001_battle
  - stageType: PvpRateStageType__3
    planType: ProducePlanType_Plan2
    turn: 10
    produceItemId: pitem_02-0-006-0-000
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_voda-001_start
    examTimelineAssetId: tln_cont_voda-001_battle
- id: pvp_rate_config-3
  description: S3
  vocal: 238
  dance: 291
  visual: 353
  examSettingId: p_exam_setting-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-contest-season_003
  examBattleFirstRankBonusPermil: 200
  pvpRateCommonProduceCardId: pvp_live_battle_1
  winTimelineAssetId: tln_cont_davi-001_totalresult_win
  loseTimelineAssetId: tln_cont_davi-001_totalresult_lose
  startTimelineInitialTimePermil: 5033
  topAssetId: contest-top-davi
  stages:
  - stageType: PvpRateStageType__1
    planType: ProducePlanType_Plan1
    turn: 10
    produceItemId: pitem_01-0-001-0-000
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_davi-001_start
    examTimelineAssetId: tln_cont_davi-001_battle
  - stageType: PvpRateStageType__2
    planType: ProducePlanType_Plan2
    turn: 8
    produceItemId: pitem_02-0-002-0-001
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_davi-001_start
    examTimelineAssetId: tln_cont_davi-001_battle
  - stageType: PvpRateStageType__3
    planType: ProducePlanType_Plan2
    turn: 8
    produceItemId: pitem_02-0-006-0-001
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_davi-001_start
    examTimelineAssetId: tln_cont_davi-001_battle
- id: pvp_rate_config-4
  description: S4
  vocal: 134
  dance: 401
  visual: 356
  examSettingId: p_exam_setting-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-contest-season_004
  examBattleFirstRankBonusPermil: 200
  pvpRateCommonProduceCardId: pvp_live_battle_1
  winTimelineAssetId: tln_cont_davi-001_totalresult_win
  loseTimelineAssetId: tln_cont_davi-001_totalresult_lose
  startTimelineInitialTimePermil: 5033
  topAssetId: contest-top-davi
  stages:
  - stageType: PvpRateStageType__1
    planType: ProducePlanType_Plan1
    turn: 10
    produceItemId: pitem_01-0-001-0-001
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_davi-001_start
    examTimelineAssetId: tln_cont_davi-001_battle
  - stageType: PvpRateStageType__2
    planType: ProducePlanType_Plan1
    turn: 10
    produceItemId: pitem_01-0-005-0-001
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_davi-001_start
    examTimelineAssetId: tln_cont_davi-001_battle
  - stageType: PvpRateStageType__3
    planType: ProducePlanType_Plan2
    turn: 8
    produceItemId: pitem_02-0-006-0-002
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_davi-001_start
    examTimelineAssetId: tln_cont_davi-001_battle
- id: pvp_rate_config-5
  description: S5
  vocal: 312
  dance: 267
  visual: 312
  examSettingId: p_exam_setting-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-contest-season_005
  examBattleFirstRankBonusPermil: 200
  pvpRateCommonProduceCardId: pvp_live_battle_1
  winTimelineAssetId: tln_cont_vovi-001_totalresult_win
  loseTimelineAssetId: tln_cont_vovi-001_totalresult_lose
  startTimelineInitialTimePermil: 5033
  topAssetId: contest-top-vovi
  stages:
  - stageType: PvpRateStageType__1
    planType: ProducePlanType_Plan1
    turn: 10
    produceItemId: pitem_01-0-001-0-001
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle
  - stageType: PvpRateStageType__2
    planType: ProducePlanType_Plan1
    turn: 12
    produceItemId: pitem_01-0-005-0-002
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle
  - stageType: PvpRateStageType__3
    planType: ProducePlanType_Plan2
    turn: 12
    produceItemId: pitem_02-0-002-0-002
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle