- id: pvp_rate_config-1
  description: 初めてのコンテスト
  vocal: 353
  dance: 238
  visual: 291
  examSettingId: p_exam_setting-1
  produceExamBattleScoreConfigId: p_exam_battle_score_config-contest-season_001
  examBattleFirstRankBonusPermil: 200
  pvpRateCommonProduceCardId: pvp_live_battle_1
  winTimelineAssetId: tln_cont_vovi-001_totalresult_win
  loseTimelineAssetId: tln_cont_vovi-001_totalresult_lose
  startTimelineInitialTimePermil: 5033
  topAssetId: contest-top-vovi
  stages:
  - stageType: PvpRateStageType__1
    planType: ProducePlanType_Common
    turn: 12
    produceItemId: pitem_00-0-004-0-000
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle
  - stageType: PvpRateStageType__2
    planType: ProducePlanType_Plan1
    turn: 8
    produceItemId: pitem_01-0-005-0-000
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle
  - stageType: PvpRateStageType__3
    planType: ProducePlanType_Plan2
    turn: 8
    produceItemId: pitem_02-0-002-0-000
    produceExamGimmickEffectGroupId: ""
    bgmAssetId: sud_bgm_produce_audition-04
    startTimelineAssetId: tln_cont_vovi-001_start
    examTimelineAssetId: tln_cont_vovi-001_battle